---
nmstate:
  dns-resolver:
    config:
      search:
        - slips.pl
      server:
        - 9.9.9.9
        - 8.8.8.8
  interfaces:
    - name: bond0
      type: bond
      state: up
      link-aggregation:
        mode: 802.3ad
        options: { miimon: 100 }
        port: [eno1, eno2, eno3, eno4]
    - name: bond0.1000
      type: vlan
      state: up
      vlan: { base-iface: bond0, id: 1000 }
    - name: br-provision
      type: linux-bridge
      state: up
      bridge:
        port:
          - name: bond0
        options:
          stp:
            enabled: false
      ipv4:
        enabled: true
        address:
          - ip: 192.168.3.1
            prefix-length: 24
    - name: br-internet
      type: linux-bridge
      state: up
      bridge:
        port:
          - name: bond0.1000
        options:
          stp:
            enabled: false
      ipv4:
        enabled: true
        dhcp: true
  routes:
    config:
      - destination: 192.168.4.0/24
        next-hop-interface: br-provision
        next-hop-address: 192.168.3.254
      - destination: 192.168.140.0/24
        next-hop-interface: br-provision
        next-hop-address: 192.168.3.254
