---
fcos_image_cache_directory: "/home/{{ ansible_user }}/.cache/openshift-installer/image_cache"
installation_directory: "~/clusterconfigs"

ansible_package_requirements:
  - nmstate
  - python3-libnmstate
  - tar
okd_package_requirements:
  - libvirt
  - qemu-kvm
  - mkisofs
  - python3-devel
  - jq
  - ipmitool

okd_repo: quay.io/openshift/okd
okd_version: stable

mirror_registry_version: 1.2.9
mirror_registry_checksum: sha256:852ea3b3efee50395344fd6fddaf3c422c435bb10120b8ee9d417c28a39070b6
mirror_registry_user: init
mirror_registry_password: "{{ lookup('password', '~/.ansible/.mirror_registry_password') }}"
mirror_registry_fqdn: "mirror-registry.{{ cluster_domain }}"
mirror_registry_quayroot: "~/mirror-registry/quay-install"
mirror_registry_authfile: "~/.config/containers/auth.json"

