---
coreos_image_cache_directory: "/home/{{ ansible_user | default(ansible_facts.user_id) }}/.cache/openshift-installer/image_cache"
installation_directory: "~/clusterconfigs"

ansible_package_requirements:
  - nmstate
  - python3-libnmstate
  - tar
okd_package_requirements:
  - libvirt
  - qemu-kvm
  - mkisofs
  - python3-devel
  - jq
  - ipmitool

# variants: [ ocp, fcos, scos ]
release_variant: scos

_release_image_repo:
  ocp: openshift-release-dev/ocp-release
  fcos: openshift/okd
  scos: okd/scos-release

_release_content_repo:
  ocp: openshift-release-dev/ocp-v4.0-art-dev
  fcos: openshift/okd-content
  scos: okd/scos-content

release_registry: quay.io
release_image_repo: "{{ _release_image_repo[release_variant] }}"
release_content_repo: "{{ _release_content_repo[release_variant] }}"
release_pull: "{{ release_registry }}/{{ release_image_repo }}:{{ release_version }}"

use_mirror_registry: true
mirror_registry_version: v2.0.0
mirror_registry_checksum: sha256:935176ee501dc72c80741257a8849efd3a8e303ed2928e71f65ce7e4a184ed57
mirror_registry_user: init
mirror_registry_password: "{{ lookup('password', '~/.ansible/.mirror_registry_password') }}"
mirror_registry_fqdn: "mirror-registry.{{ cluster_domain }}"
mirror_registry_quayroot: "~/mirror-registry/quay-install"
mirror_registry_authfile: "~/.config/containers/auth.json"
