---
coreos_image_cache_directory: "/home/{{ ansible_user }}/.cache/openshift-installer/image_cache"
installation_directory: "~/clusterconfigs"

ansible_package_requirements:
  - nmstate
  - python3-libnmstate
  - tar
okd_package_requirements:
  - libvirt
  - qemu-kvm
  - mkisofs
  - python3-devel
  - jq
  - ipmitool

use_ocp: false
release_registry: quay.io
release_repo: "{{ use_ocp | ternary('openshift-release-dev', 'openshift') }}"
release_name: "{{ use_ocp | ternary('ocp-release', 'okd') }}"
#release_version:
release_pull: "{{ release_registry }}/{{ release_repo }}/{{ release_name }}:{{ release_version }}"
release_content_source: "{{ use_ocp | ternary('ocp-v4.0-art-dev', 'okd-content') }}"

use_mirror_registry: true
mirror_registry_version: v1.3.10
mirror_registry_checksum: sha256:c9e9865ec4bfec1aa4d42cc92914d624291b4525258c4f6ce854a756d65a5034
mirror_registry_user: init
mirror_registry_password: "{{ lookup('password', '~/.ansible/.mirror_registry_password') }}"
mirror_registry_fqdn: "mirror-registry.{{ cluster_domain }}"
mirror_registry_quayroot: "~/mirror-registry/quay-install"
mirror_registry_authfile: "~/.config/containers/auth.json"
