---
- hosts:
    - quay

  vars:
    quay_token: "{{ lookup('file', quay_hostname ~ '.token') }}"

  tasks:
    - name: Login or create
      block:
        - name: Create registry login
          containers.podman.podman_login:
            username: "{{ quay_init_username | default('admin') }}"
            password: "{{ quay_init_password | default('password') }}"
            registry: "{{ quay_hostname }}"
      rescue:
        - name: Create initial user
          uri:
            url: "https://{{ quay_hostname }}/api/v1/user/initialize"
            method: POST
            body_format: json
            body:
              username: "{{ quay_init_username | default('admin') }}"
              password: "{{ quay_init_password | default('password') }}"
              email: "{{ quay_init_email | default('init@quay.io') }}"
              access_token: true
            return_content: true
          register: _initial_user  # The token we receive here is valid for 1-2 hours

        - name: Set quay_token
          set_fact:
            quay_token: "{{ _initial_user.json.access_token }}"

        - name: Create registry login
          containers.podman.podman_login:
            username: "{{ quay_init_username | default('admin') }}"
            password: "{{ quay_init_password | default('password') }}"
            registry: "{{ quay_hostname }}"

    - name: Initial configuration
      when: _initial_user is defined
      block:
        - name: Get organizations
          uri:
            url: "https://{{ quay_hostname }}/api/v1/superuser/organizations/"
            headers:
              Authorization: "Bearer {{ quay_token }}"
            return_content: true
          register: _orgs

        - name: Create (missing) organizations
          when: "organization not in _orgs.json.organizations | map(attribute='name')"
          uri:
            url: "https://{{ quay_hostname }}/api/v1/organization/"
            headers:
              Authorization: "Bearer {{ quay_token }}"
            method: POST
            body_format: json
            body:
              name: "{{ organization }}"
            return_content: true
            status_code: 201
          changed_when: true
          loop_control:
            loop_var: organization
          loop:
            - mirrors
            - proxy-quay.io

        - name: Get proxycache for proxy-quay.io
          uri:
            url: "https://{{ quay_hostname }}/api/v1/organization/proxy-quay.io/proxycache"
            headers:
              Authorization: "Bearer {{ quay_token }}"
            return_content: true
          register: _proxy_cache

        - name: Create proxycache for proxy-quay.io
          when: _proxy_cache.json.upstream_registry != 'quay.io'
          uri:
            url: "https://{{ quay_hostname }}/api/v1/organization/proxy-quay.io/proxycache"
            headers:
              Authorization: "Bearer {{ quay_token }}"
              Content-Type: "application/json"
            method: POST
            body_format: json
            body:
              org_name: "proxy-quay.io"  # https://issues.redhat.com/browse/PROJQUAY-9042
              upstream_registry: "quay.io"
            return_content: true
            status_code: 201
          changed_when: true
          register: _res
        - debug:
            var: _res
