---
- name: Initialize fresh MAAS boxes for Openstack
  hosts:
    - openstack
  become: true

  vars:
    proxy_env:
      http_proxy: "http://192.168.3.1:8000"
      https_proxy: "http://192.168.3.1:8000"

  roles:
    - serial-getty
