---
maas:
  hosts:
    messy-maas:
      ansible_host: 192.168.3.1
      ansible_ssh_common_args: '-o ProxyJump=messy-maas'
      maas:
        fabrics:
          fabric-0:
            vlan.2: { name: amplifi, subnet: 10.0.0.0/24 }
            vlan.3: { name: maas,    subnet: 192.168.3.0/24 }
            vlan.4: { name: bmc,     subnet: 192.168.4.0/24 }
            vlan.10: { name: mgmt,    mtu: 9000, subnet: 172.29.236.0/22 }
            vlan.20: { name: storage, mtu: 9000, subnet: 172.29.244.0/22 }
            vlan.30: { name: vxlan,   mtu: 9000, subnet: 172.29.240.0/22 }
            vlan.40: { name: dbaas,   mtu: 9000, subnet: 172.29.232.0/22 }
            vlan.50: { name: lbaas,   mtu: 9000, subnet: 172.29.252.0/22 }
