---
okd:
  hosts:
    provisioner:
  children:
    okd_masters:
      hosts:
        famous-koi: #master-0:
        grand-worm: #master-1:
        wise-grebe: #master-2:
    okd_workers:
      hosts:
        new-vervet: #worker-0:

uio_okd:
  hosts:
    uio-provisioner:
  children:
    uio_okd_masters:
      hosts:
        master-0:
        master-1:
        master-2:
    uio_okd_workers:
      hosts:
        worker-0:
        worker-1:
        worker-2:
