---
okd:
  hosts:
    famous-koi: # master-0:
    grand-worm: # master-1:
    wise-grebe: # master-2:
    new-vervet: # worker-0:
  children:
    okd_masters:
      hosts:
        famous-koi: #master-0:
        grand-worm: #master-1:
        wise-grebe: #master-2:
    okd_workers:
      hosts:
        new-vervet: #worker-0
