---
openstack:
  hosts:
    cool-gator:
      ansible_user: ubuntu
      ansible_host: 192.168.3.2
      ansible_ssh_common_args: '-o ProxyJump=messy-maas'
      network:
        ethernets:
          eno1:   { set-name: eth0, match: { macaddress: "c4:34:6b:b5:ad:80" }, native_vlan: 3 }
          eno2:   { set-name: eth1, match: { macaddress: "c4:34:6b:b5:ad:81" }, native_vlan: 3 }
          eno3:   { set-name: eth2, match: { macaddress: "c4:34:6b:b5:ad:82" }, native_vlan: 3 }
          eno4:   { set-name: eth3, match: { macaddress: "c4:34:6b:b5:ad:83" }, native_vlan: 3 }
          ens3f0: { set-name: sfp0, match: { macaddress: "a0:36:9f:93:86:78" }, native_vlan: 0 }
          ens3f1: { set-name: sfp1, match: { macaddress: "a0:36:9f:93:86:7a" }, native_vlan: 0 }
        bonds:
          bond0:
            interfaces: ['eth0', 'eth1', 'eth2', 'eth3']
            parameters: { mode: 802.3ad }
          bond1:
            interfaces: ['sfp0', 'sfp1']
            parameters: { mode: 802.3ad }
        vlans:
          bond0.1000: { id: 1000, link: bond0 }
          bond1.10:   { id:   10, link: bond1 }
          bond1.20:   { id:   20, link: bond1 }
          bond1.21:   { id:   21, link: bond1 }
          bond1.30:   { id:   30, link: bond1 }
        bridges:
          br-provision:
            interfaces: ['bond0']
            addresses: ['192.168.3.2/24']
          br-internet:
            interfaces: ['bond0.1000']
          br-mgmt:
            interfaces: ['bond1.10']
            addresses: ['172.29.236.2/22']
          br-storage:
            interfaces: ['bond1.20']
            addresses: ['172.29.244.2/22']
          br-iscsi:
            interfaces: ['bond1.21']
            addresses: ['172.16.21.2/24']
          br-tunnel:
            interfaces: ['bond1.30']
            addresses: ['172.29.240.2/22']
          br-vlan:
            interfaces: ['bond1']
      #boot_disk: sda
      lvm_volumes:
        sdb: { data_vg: ceph-4752d64f-11f0-485e-99f6-2f46909fb898, data: osd-block-908fd4a5-e9d0-429e-b7eb-dac798a72e01 }
        sdc: { data_vg: ceph-059c52a5-e63c-455a-96c4-dee9f646b637, data: osd-block-3f1b6b56-b56b-46ad-961c-3c8207c82172 }
        sdd: { data_vg: ceph-61056785-53b2-45db-9a99-2940988cae25, data: osd-block-88bb9566-7d59-4bfc-8216-53c95f716f2a }
        sde: { data_vg: ceph-4610ed10-59e6-48ad-ba88-d364911e8ed6, data: osd-block-1a6e9889-b687-46d7-b344-edff6354a29e }
        sdf: { data_vg: ceph-0154baad-8168-46dd-a7dd-8fe7e1998013, data: osd-block-b74260ba-3bf4-43b0-b81f-07def6101bf9 }
        sdg: { data_vg: ceph-9d0b2340-6e64-4d1a-a91a-1e0880fbd046, data: osd-block-058296de-3b32-474c-aef0-239c0f8e822a }
    key-shrimp:
      ansible_user: ubuntu
      ansible_host: 192.168.3.3
      ansible_ssh_common_args: '-o ProxyJump=messy-maas'
      network:
        ethernets:
          eno1:   { set-name: eth0, match: { macaddress: "c4:34:6b:b5:ad:4c" }, native_vlan: 3 }
          eno2:   { set-name: eth1, match: { macaddress: "c4:34:6b:b5:ad:4d" }, native_vlan: 3 }
          eno3:   { set-name: eth2, match: { macaddress: "c4:34:6b:b5:ad:4e" }, native_vlan: 3 }
          eno4:   { set-name: eth3, match: { macaddress: "c4:34:6b:b5:ad:4f" }, native_vlan: 3 }
          ens3f0: { set-name: sfp0, match: { macaddress: "a0:36:9f:93:85:40" }, native_vlan: 0 }
          ens3f1: { set-name: sfp1, match: { macaddress: "a0:36:9f:93:85:42" }, native_vlan: 0 }
        bonds:
          bond0:
            interfaces: ['eth0', 'eth1', 'eth2', 'eth3']
            parameters:
              mode: 802.3ad
          bond1:
            interfaces: ['sfp0', 'sfp1']
            parameters:
              mode: 802.3ad
        vlans:
          bond0.1000: { id: 1000, link: bond0 }
          bond1.10:   { id:   10, link: bond1 }
          bond1.20:   { id:   20, link: bond1 }
          bond1.21:   { id:   21, link: bond1 }
          bond1.30:   { id:   30, link: bond1 }
        bridges:
          br-provision:
            interfaces: ['bond0']
            addresses: ['192.168.3.3/24']
          br-internet:
            interfaces: ['bond0.1000']
          br-mgmt:
            interfaces: ['bond1.10']
            addresses: ['172.29.236.3/22']
          br-storage:
            interfaces: ['bond1.20']
            addresses: ['172.29.244.3/22']
          br-iscsi:
            interfaces: ['bond1.21']
            addresses: ['172.16.21.3/24']
          br-tunnel:
            interfaces: ['bond1.30']
            addresses: ['172.29.240.3/22']
          br-vlan:
            interfaces: ['bond1']
      #boot_disk: sda
      lvm_volumes:
        sdb: { data_vg: ceph-907b30cd-9380-4b1a-847a-da292073179e, data: osd-block-c39a9ed4-c1fa-43df-9533-e90c571facfe }
        sdc: { data_vg: ceph-e97f5be3-5c21-4b19-b02e-a4098f13dde8, data: osd-block-ce53d78f-6c7f-48a3-a32a-1e575bed4c4e }
        sdd: { data_vg: ceph-9f4ed8e4-4a42-430a-9090-e63150305528, data: osd-block-628c58a2-c36e-4aec-971c-5d4994d870a1 }
        sde: { data_vg: ceph-277d6ed6-a0c7-47a6-b313-6ca58c1de23c, data: osd-block-91060bae-30f1-4ba6-8744-674d6629e6e8 }
        sdf: { data_vg: ceph-6f3b9fd7-914a-446d-8e1f-b8a96dc1da8d, data: osd-block-d905818d-5fc7-4680-ae7f-5f1ccd1485a2 }
        sdg: { data_vg: ceph-d63b323b-c34c-4a73-bb52-c343af1fdae7, data: osd-block-5a6694df-b101-4643-9152-f43e231e6566 }
    mint-panda:
      ansible_user: ubuntu
      ansible_host: 192.168.3.4
      ansible_ssh_common_args: '-o ProxyJump=messy-maas'
      network:
        ethernets:
          eno1:   { set-name: eth0, match: { macaddress: "c4:34:6b:b6:a1:e0" }, native_vlan: 3 }
          eno2:   { set-name: eth1, match: { macaddress: "c4:34:6b:b6:a1:e1" }, native_vlan: 3 }
          eno3:   { set-name: eth2, match: { macaddress: "c4:34:6b:b6:a1:e2" }, native_vlan: 3 }
          eno4:   { set-name: eth3, match: { macaddress: "c4:34:6b:b6:a1:e3" }, native_vlan: 3 }
          ens3f0: { set-name: sfp0, match: { macaddress: "00:1b:21:bc:f6:8c" }, native_vlan: 0 }
          ens3f1: { set-name: sfp1, match: { macaddress: "00:1b:21:bc:f6:8d" }, native_vlan: 0 }
        bonds:
          bond0:
            interfaces: ['eth0', 'eth1', 'eth2', 'eth3']
            parameters:
              mode: 802.3ad
          bond1:
            interfaces: ['sfp0', 'sfp1']
            parameters:
              mode: 802.3ad
        vlans:
          bond0.1000: { id: 1000, link: bond0 }
          bond1.10:   { id:   10, link: bond1 }
          bond1.20:   { id:   20, link: bond1 }
          bond1.21:   { id:   21, link: bond1 }
          bond1.30:   { id:   30, link: bond1 }
        bridges:
          br-provision:
            interfaces: ['bond0']
            addresses: ['192.168.3.4/24']
          br-internet:
            interfaces: ['bond0.1000']
          br-mgmt:
            interfaces: ['bond1.10']
            addresses: ['172.29.236.4/22']
          br-storage:
            interfaces: ['bond1.20']
            addresses: ['172.29.244.4/22']
          br-iscsi:
            interfaces: ['bond1.21']
            addresses: ['172.16.21.4/24']
          br-tunnel:
            interfaces: ['bond1.30']
            addresses: ['172.29.240.4/22']
          br-vlan:
            interfaces: ['bond1']
      #boot_disk: sda
      lvm_volumes:
        sdb: { data_vg: ceph-011f7cd9-70bd-42b5-9bd8-d835612f8149, data: osd-block-933ece62-b044-4bfd-a000-246139997d3d }
        sdc: { data_vg: ceph-d97c3f88-b2c0-410a-8408-93fe89dc54d5, data: osd-block-7e79eeaa-9c2f-4578-a06e-4f3044cb6a1d }
        sdd: { data_vg: ceph-478ff938-df47-44f8-928e-1ad2d40536fb, data: osd-block-4d67e245-c553-4894-98fe-6cdd810df293 }
        sde: { data_vg: ceph-0df98438-7560-4eae-b89a-21047de61d99, data: osd-block-c4a26cec-3866-4efd-ad20-13388f0bcc46 }
        sdf: { data_vg: ceph-777f082f-a0d2-48bb-ab38-8e6562cc93df, data: osd-block-c82d1c69-130f-4ee7-baea-96aef3d7a04b }
        sdg: { data_vg: ceph-83caf155-0365-4f58-a6a9-f6bbb1f4e2a5, data: osd-block-0b735bd7-7736-4e23-b9de-912a29e2316f }
    novel-dodo:
      ansible_user: ubuntu
      ansible_host: 192.168.3.5
      ansible_ssh_common_args: '-o ProxyJump=messy-maas'
      network:
        ethernets:
          eno1:   { set-name: eth0, match: { macaddress: "c4:34:6b:ad:74:a0" }, native_vlan: 3 }
          eno2:   { set-name: eth1, match: { macaddress: "c4:34:6b:ad:74:a1" }, native_vlan: 3 }
          eno3:   { set-name: eth2, match: { macaddress: "c4:34:6b:ad:74:a2" }, native_vlan: 3 }
          eno4:   { set-name: eth3, match: { macaddress: "c4:34:6b:ad:74:a3" }, native_vlan: 3 }
          ens3f0: { set-name: sfp0, match: { macaddress: "00:1b:21:bc:f6:9a" }, native_vlan: 0 }
          ens3f1: { set-name: sfp1, match: { macaddress: "00:1b:21:bc:f6:9b" }, native_vlan: 0 }
        bonds:
          bond0:
            interfaces: ['eth0', 'eth1', 'eth2', 'eth3']
            parameters:
              mode: 802.3ad
          bond1:
            interfaces: ['sfp0', 'sfp1']
            parameters:
              mode: 802.3ad
        vlans:
          bond0.1000: { id: 1000, link: bond0 }
          bond1.10:   { id:   10, link: bond1 }
          bond1.20:   { id:   20, link: bond1 }
          bond1.21:   { id:   21, link: bond1 }
          bond1.30:   { id:   30, link: bond1 }
        bridges:
          br-provision:
            interfaces: ['bond0']
            addresses: ['192.168.3.5/24']
          br-internet:
            interfaces: ['bond0.1000']
          br-mgmt:
            interfaces: ['bond1.10']
            addresses: ['172.29.236.5/22']
          br-storage:
            interfaces: ['bond1.20']
            addresses: ['172.29.244.5/22']
          br-iscsi:
            interfaces: ['bond1.21']
            addresses: ['172.16.21.5/24']
          br-tunnel:
            interfaces: ['bond1.30']
            addresses: ['172.29.240.5/22']
          br-vlan:
            interfaces: ['bond1']
      #boot_disk: sda
      lvm_volumes:
        sdb: { data_vg: ceph-5931b19d-c70b-42a8-a9e4-aa6f3711d8cc, data: osd-block-42d8df22-1c86-4edc-8ee8-d5867f3db7e8 }
        sdc: { data_vg: ceph-3d57b761-d205-412d-9a65-71c6651600e9, data: osd-block-c98b7737-be5f-4d47-aaf0-e9545fda8d23 }
        sdd: { data_vg: ceph-66ab96e8-eb37-44ad-87c8-b6bb421bf639, data: osd-block-52a42b8f-8666-4bab-b922-2ab06cde50d4 }
        sde: { data_vg: ceph-4f20e4c1-0d7d-48e4-8d2b-746aa1843399, data: osd-block-9e89812a-b75a-4c62-ac95-d230ef975e2a }
        sdf: { data_vg: ceph-57f15f56-4143-44b6-b22b-87c475bca255, data: osd-block-88acafd7-36a5-40ee-8e45-69ac96a28305 }
        sdg: { data_vg: ceph-4abeb42a-ae1c-4185-86c6-e75744544296, data: osd-block-eb890222-41d0-4e16-864b-78028b48f188 }
