---
provisioning:
  hosts:
    maas:
      ansible_host: 192.168.3.11
      #ansible_ssh_common_args: '-o ProxyJump=messy-maas'
      maas_network:
        fabrics:
          - name: copper
            remap: fabric-0
            vlans:
              - { id: 2, name: amplifi, mtu: 1500, subnets: [ { cidr: 192.168.140.0/24 } ] }
              - id: 3
                name: provision
                mtu: 1500
                subnets:
                  - cidr: 192.168.3.0/24
                    ip_ranges:
                      - { type: dynamic, start_ip: 192.168.3.200, end_ip: 192.168.3.249 }
                dhcp_on: true
              - { id: 4,    name: bmc,      mtu: 1500, subnets: [ { cidr: 192.168.4.0/24  } ] }
              - { id: 10,   name: mgmt,     mtu: 9000, subnets: [ { cidr: 172.29.236.0/22 } ] }
              - { id: 20,   name: storage,  mtu: 9000, subnets: [ { cidr: 172.29.244.0/22 } ] }
              - { id: 21,   name: iscsi,    mtu: 9000, subnets: [ { cidr: 192.168.21.0/24 } ] }
              - { id: 30,   name: tunnel,   mtu: 9000, subnets: [ { cidr: 172.29.240.0/22 } ] }
              - { id: 40,   name: dbaas,    mtu: 9000, subnets: [ { cidr: 172.29.232.0/22 } ] }
              - { id: 50,   name: lbaas,    mtu: 9000, subnets: [ { cidr: 172.29.252.0/22 } ] }
              - { id: 1000, name: internet, mtu: 1500 }
          - name: fiber
            remap: fabric-1
            vlans:
              - { id: 1000, name: internet, mtu: 1500 }
    foreman:
      ansible_host: 192.168.3.12
    bifrost8:
      ansible_host: 192.168.3.13
    bifrost9:
      ansible_host: 192.168.3.14
    foreman8:
      ansible_host: 192.168.3.15
    foreman9:
      ansible_host: 192.168.3.16
