---
- name: Set ocp_stable_version
  when: ocp_stable_version is not defined
  block:
    - name: Query ocp/stable/release.txt for latest stable version
      uri:
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/release.txt
        return_content: true
      environment: "{{ hostvars[inventory_hostname].environment | default({}) }}"
      register: _ocp_stable_release

    - name: set_fact ocp_stable_version
      set_fact:
        ocp_stable_version: "{{ _ocp_stable_release.content | regex_search(q_release_version, '\\1') | first }}"
      vars:
        q_release_version: "Name:\\s+(.*)"

- name: Get release_pull for OCP
  when:
    - release_variant == 'ocp'
    - release_pull is not search('@sha256')
  block:
    - name: "Query ocp/{{ release_version | default(ocp_stable_version) }}/release.txt"
      uri:
        url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ release_version | default(ocp_stable_version) }}/release.txt"
        return_content: true
      environment: "{{ hostvars[inventory_hostname].environment | default({}) }}"
      register: _ocp_release

    - name: Set release_pull
      when:
      set_fact:
        release_version: "{{ _ocp_release.content | regex_search(q_release_version, '\\1') | first }}"
        release_pull: "{{ _ocp_release.content | regex_search(q_pull_from, '\\1') | first }}"
      vars:
        q_pull_from: "Pull [Ff]rom:\\s+(.*)"
        q_release_version: "Name:\\s+(.*)"

- name: Get release_version for okd
  when:
    - release_variant != 'ocp'
    - release_version is not defined
  block:
    - name: query origin-release api for latest 4-stable version
      uri:
        url: "{{ release_url[release_variant] }}"
        return_content: true
      register: _latest
      environment: "{{ hostvars[inventory_hostname].environment | default({}) }}"
      vars:
        release_url:
          fcos: "https://amd64.origin.releases.ci.openshift.org/api/v1/releasestream/4-stable/latest"
          scos: "https://amd64.origin.releases.ci.openshift.org/api/v1/releasestream/4-scos-stable/latest"

    - name: Set release_version
      set_fact:
        release_version: "{{ _latest.json.name }}"

