---
# https://docs.okd.io/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html
- name: install packages
  package:
    name: "{{ ansible_package_requirements +
              okd_package_requirements }}"
  become: true

# TODO: EL9 (almalinux) removes /var/run/libvirt/libvirt-sock when
# "not in use" under /usr/lib/systemd/system/libvirtd.socket
#- block:
#    - stat:
#        path: /var/run/libvirt/libvirt-sock
#      register: _stat_libvirt_sock
#    - debug:
#        var: _stat_libvirt_sock
#
#    - name: disable the systemd.socket
#      ansible.builtin.systemd:
#        name: libvirtd.socket
#        enabled: false
#        state: stopped
#        masked: false
#      become: true
#      register: _libvirtd_socket
#
#    - name: enable libvirt
#      ansible.builtin.systemd:
#        name: libvirtd
#        enabled: true
#        state: "{{ (_libvirtd_socket is changed) | ternary('restarted', 'started') }}"
#      become: true
#  tags:
#    - libvirt

# FIXME: this currently breaks the network, maybe look into nmstate?
#- import_tasks: network.yml

- import_tasks: user.yml

- name: get release_version for ocp
  block:
    - name: query ocp/stable/release.txt for latest stable version
      uri:
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ ocp_version | default('stable') }}/release.txt
        return_content: true
      environment: "{{ hostvars[inventory_hostname].environment | default({}) }}"
      register: _get

    - name: set_fact ocp_version
      set_fact:
        ocp_version: "{{ _get.content | regex_search(q_release_version, '\\1') | first }}"
      vars:
        q_release_version: "Name:\\s+(.*)"

- when: okd_release is not defined
  block:
    - name: query origin-release api for latest 4-stable version
      uri:
        url: https://amd64.origin.releases.ci.openshift.org/api/v1/releasestream/4-stable/latest
        return_content: true
      register: _latest
      environment: "{{ hostvars[inventory_hostname].environment | default({}) }}"

    - name: set_fact okd_release
      set_fact:
        okd_release: "{{ _latest.json.name }}"

- import_tasks: tools.yml
  tags:
    - tools

- import_tasks: mirror-registry.yml
- import_tasks: install.yml
