---
- name: get latest official openshift-client
  delegate_to: "{{ host }}"
  environment: "{{ hostvars[host].environment | default({}) }}"
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ okd_version | default('stable') }}/openshift-client-linux.tar.gz"
    # checksum: "sha256:https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ okd_version | default('stable') }}/sha256sum.txt"
    dest: "~/openshift-client-linux.tar.gz"
    mode: '0644'
  loop:
    - localhost
    - "{{ inventory_hostname }}"
  loop_control:
    loop_var: host

- name: install latest openshift-client to .local/bin
  delegate_to: "{{ host }}"
  unarchive:
    src: "~/openshift-client-linux.tar.gz"
    remote_src: true
    dest: "~/.local/bin"
    exclude:
      - README.md
    creates: "~/.local/bin/oc"
  loop:
    - localhost
    - "{{ inventory_hostname }}"
  loop_control:
    loop_var: host

- name: get latest official opm
  delegate_to: "{{ host }}"
  environment: "{{ hostvars[host].environment | default({}) }}"
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ okd_version | default('stable') }}/opm-linux.tar.gz"
    # checksum: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ okd_version | default('stable') }}/sha256sum.txt"
    dest: "~/opm-linux.tar.gz"
    mode: '0644'
  loop:
    - localhost
    - "{{ inventory_hostname }}"
  loop_control:
    loop_var: host

- name: install latest opm to .local/bin
  delegate_to: "{{ host }}"
  unarchive:
    src: "~/opm-linux.tar.gz"
    remote_src: true
    dest: "~/.local/bin"
    exclude:
      - README.md
    creates: "~/.local/bin/opm"
  loop:
    - localhost
    - "{{ inventory_hostname }}"
  loop_control:
    loop_var: host

- name: get openshift client/installer for {{ okd_release }}
  environment: "{{ hostvars[inventory_hostname].environment | default({}) }}"
  command: "oc adm release extract --tools {{ okd_repo }}:{{ okd_release }}"
  args:
    creates: openshift-client-linux-{{ okd_release }}.tar.gz

- name: update openshift client/installer to {{ okd_release }}
  unarchive:
    src: "~/{{ item }}"
    remote_src: true
    dest: "~/.local/bin"
    exclude:
      - README.md
  loop:
    - "openshift-client-linux-{{ okd_release }}.tar.gz"
    - "openshift-install-linux-{{ okd_release }}.tar.gz"

- name: get openshift-baremetal-install for {{ okd_release }}
  environment: "{{ hostvars[inventory_hostname].environment | default({}) }}"
  command: "oc adm release extract --command=openshift-baremetal-install --to ~/.local/bin {{ okd_repo }}:{{ okd_release }}"
  args:
    creates: "~/.local/bin/openshift-baremetal-install"

- name: get bash-completion script for openshift commands
  command: "{{ command }} completion bash"
  changed_when: false
  loop:
    - oc
    - openshift-install
    - openshift-baremetal-install
    - opm
  loop_control:
    loop_var: command
  register: _command_completion

- name: save bash-completion scripts for openshift commands
  copy:
    content: "{{ item.stdout }}"
    dest: "~/.local/share/bash-completion/completions/{{ item.command }}"
    mode: '0644'
  loop: "{{ _command_completion.results }}"
  loop_control:
    label: "{{ item.command }}"
