---
- name: get latest official openshift-client
  environment: "{{ hostvars[inventory_hostname].environment | default({}) }}"
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-client-linux-{{ ocp_version }}.tar.gz"
    checksum: "sha256:https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ ocp_version }}/sha256sum.txt"
    dest: "~/openshift-client-linux.tar.gz"
    mode: '0644'

- name: install latest openshift-client to .local/bin
  unarchive:
    src: "~/openshift-client-linux.tar.gz"
    remote_src: true
    dest: "~/.local/bin"
    exclude:
      - README.md
    creates: "~/.local/bin/oc"

- name: get latest official opm
  environment: "{{ hostvars[inventory_hostname].environment | default({}) }}"
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ ocp_version }}/opm-linux-{{ ocp_version }}.tar.gz"
    checksum: "sha256:https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ ocp_version }}/sha256sum.txt"
    dest: "~/opm-linux.tar.gz"
    mode: '0644'

- name: install latest opm to .local/bin
  unarchive:
    src: "~/opm-linux.tar.gz"
    remote_src: true
    dest: "~/.local/bin"
    exclude:
      - README.md
    creates: "~/.local/bin/opm"

- name: get openshift client/installer for {{ release_version }}
  environment: "{{ hostvars[inventory_hostname].environment | default({}) }}"
  command: "oc adm release extract --tools {{ release_pull }}"
  args:
    chdir: "~/"
    creates: "~/openshift-client-linux-{{ release_version }}.tar.gz"

- name: update openshift client/installer to {{ release_version }}
  unarchive:
    src: "~/{{ item }}"
    remote_src: true
    dest: "~/.local/bin"
    exclude:
      - README.md
  loop:
    - "openshift-client-linux-{{ release_version }}.tar.gz"
    - "openshift-install-linux-{{ release_version }}.tar.gz"

- name: get openshift-baremetal-install for {{ release_version }}
  environment: "{{ hostvars[inventory_hostname].environment | default({}) }}"
  command: >-
    oc adm release extract --command=openshift-baremetal-install
      --to ~/.local/bin {{ release_pull }}
#  args:
#    creates: "~/.local/bin/openshift-baremetal-install"
  tags:
    - baremetal

- name: get bash-completion script for openshift commands
  command: "{{ command }} completion bash"
  changed_when: false
  loop:
    - oc
    - openshift-install
    - openshift-baremetal-install
    - opm
  loop_control:
    loop_var: command
  register: _command_completion

- name: save bash-completion scripts for openshift commands
  copy:
    content: "{{ item.stdout }}"
    dest: "~/.local/share/bash-completion/completions/{{ item.command }}"
    mode: '0644'
  loop: "{{ _command_completion.results }}"
  loop_control:
    label: "{{ item.command }}"
