---
- name: create user
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - wheel
      - libvirt
  become: true

#- name: apply to sudoers
#  community.general.sudoers:
#    name: "{{ user }}"
#    user: "{{ user }}"
#    commands: ALL
#    runas: root
#  become: true

- name: create needed directories (if missing)
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items:
    - path: "~/.local/bin"
    - path: "~/.local/share/bash-completion/completions"
    - path: "~/.ssh"
      mode: '0700'

- name: generate ssh-key
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_ed25519"
    type: "ed25519"
    regenerate: full_idempotence
  register: _ssh_key
  tags:
    - config
    - install-config.yaml

- name: install my key for virt-mgmt
  become: true
  ansible.posix.authorized_key:
    user: root
    key: "{{ lookup('file', item) }}"
  with_first_found:
    - "~/.ssh/id_ed25519.pub"
    - "~/.ssh/id_ecdsa.pub"
    - "~/.ssh/id_rsa.pub"
