---
okd_external_ipv4_addr: "172.28.4.9"
okd_external_ipv6_addr: "2001:700:100:8492::9"

bootMACAddress: "{{ interfaces.eno1 }}"
bootMode: UEFI

rootDeviceHints:
  wwnWithExtension: "0x6c81f660d39042002c7a3a360eea492b"
  #hctl: "6:2:0:0"
  #hctl: "0:2:0:0"
