---
base_domain: slips.pl
cluster_name: okd
cluster_domain: "{{ cluster_name }}.{{ base_domain }}"

master_group: okd_masters
worker_group: okd_workers

routes:
  - 192.168.4.0/24,192.168.100.254
  - 192.168.140.0/24,192.168.100.254

baremetal_network_cidr: 192.168.100.0/24
