---
base_domain: uio.no
cluster_name: openshift-utv
cluster_domain: "{{ cluster_name }}.{{ base_domain }}"

master_group: uio_okd_masters
worker_group: uio_okd_workers

baremetal_network_cidr: 172.28.4.0/24

dns_servers:
  - 129.240.2.27
  - 129.240.2.40

#okd_release: 4.12.0-0.okd-2023-04-16-041331
use_fcos_image_cache: true
mirror_registry_fqdn: "mirror-registry.{{ cluster_domain }}"
