---
base_domain: uio.no
cluster_name: openshift-utv
cluster_domain: "{{ cluster_name }}.{{ base_domain }}"

master_group: uio_okd_masters
worker_group: uio_okd_workers

baremetal_network_cidr: 172.28.4.0/24

dns_servers:
  - 129.240.2.27
  - 129.240.2.40

use_coreos_image_cache: true
mirror_registry_fqdn: "mirror-registry.{{ cluster_domain }}"

release_version: 4.13.0-0.okd-2023-08-04-164726

# Use Openshift Container Platform
# use_ocp: true
# pullSecret: "{{ lookup('file', 'pull-secret-ocp.json') | to_nice_json }}"
