---
base_domain: uio.no
cluster_name: openshift-utv
cluster_domain: "{{ cluster_name }}.{{ base_domain }}"

master_group: uio_okd_masters
worker_group: uio_okd_workers

baremetal_network_ipv4_cidr: "172.28.4.0/24"
baremetal_network_ipv6_cidr: "2001:700:100:8492::/64"
enable_ipv6: true

#use_coreos_image_cache: true
#coreos_meta_location: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/39.20240104.3.0/x86_64/fedora-coreos-39.20240104.3.0-qemu.x86_64.qcow2.xz
#coreos_meta_sha256: b2e4c07b8ac0e96b39af58f7daef9829536b534ce6e774dc14d54bcce000a81c
#coreos_meta_uncompressed_sha256: 280ee50c8b3f932fbe2cd903adb592b83de6f66910152bcd092e483d8cc193fa

#release_variant: fcos
#release_version: 4.13.0-0.okd-2023-10-28-065448
#release_version: 4.14.0-0.okd-2024-01-26-175629
#release_version: 4.15.0-0.okd-2024-03-10-010116

#release_variant: scos
#release_version: 4.16.0-okd-scos.1
#release_version: 4.17.0-okd-scos.3
#release_version: 4.18.0-okd-scos.7

#release_variant: ocp
#release_version: 4.16.13
#release_pull: quay.io/openshift-release-dev/ocp-release@sha256:6078cb4ae197b5b0c526910363b8aff540343bfac62ecb1ead9e068d541da27b
#pullSecret: "{{ lookup('file', 'pull-secret-ocp.json') | to_nice_json }}"
#fix_ostree_auth: false
