---
base_domain: uio.no
cluster_name: openshift-utv
cluster_domain: "{{ cluster_name }}.{{ base_domain }}"

master_group: uio_okd_masters
worker_group: uio_okd_workers

baremetal_network_cidr: 172.28.4.0/24

dns_servers:
  - 129.240.2.27
  - 129.240.2.40

use_coreos_image_cache: true
#coreos_meta_location: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/39.20240104.3.0/x86_64/fedora-coreos-39.20240104.3.0-qemu.x86_64.qcow2.xz
#coreos_meta_sha256: b2e4c07b8ac0e96b39af58f7daef9829536b534ce6e774dc14d54bcce000a81c
#coreos_meta_uncompressed_sha256: 280ee50c8b3f932fbe2cd903adb592b83de6f66910152bcd092e483d8cc193fa

mirror_registry_fqdn: "mirror-registry.{{ cluster_domain }}"

#release_version: 4.13.0-0.okd-2023-10-28-065448
release_version: 4.14.0-0.okd-2024-01-26-175629
#release_version: 4.15.0-0.okd-2024-03-10-010116

# Use Openshift Container Platform
# use_ocp: true
# pullSecret: "{{ lookup('file', 'pull-secret-ocp.json') | to_nice_json }}"
